export const MARKERS = {
  click: "📍",
  dot: "𓈒",
  farmácia: "💊",
  restaurante: "🍴",
  escola: "🏫",
  igreja: "⛪",
  hospital: "🏥",
  clínica_médica: "🏥",
  academia: "🏋️‍♀️",
  super_mercado: "🛒",
  padaria: "🍞",
  banco: "🏦",
  posto_de_gasolina: "⛽",
  açougue: "🍖",
};
