export const markers = {
  click: "📍",
  dot: "𓈒",
  Farmácia: "💊",
  Restaurante: "🍴",
  Escola: "🏫",
  Igreja: "⛪",
  Hospital: "🏥",
  Clínica_médica: "🏥",
  Academia: "🏋️‍♀️",
  Supermercado: "🛒",
  Padaria: "🍞",
  Banco: "🏦",
  Posto_De_gasolina: "⛽",
  Açougue: "🍖",
};
